groups:
  - name: Instance Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 2m
        labels:
          severity: "critical"
        annotations:
          summary: Instance {{ $labels.instance }} is down
          description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 2 minutes. Node seems down.
      - alert: HostHighCpuLoad
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host high CPU load (instance {{ $labels.instance }})"
          description: "CPU load is > 80%"
      - alert: HostOutOfMemory
        expr: (sum(node_memory_MemAvailable_bytes) BY (instance) / sum(node_memory_MemTotal_bytes) BY (instance) * 100) < 10
        #expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host out of memory (instance {{ $labels.instance }})"
          description: "Node memory is filling up (< 10% left)"
          #description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: HostMemoryUnderMemoryPressure
        expr: rate(node_vmstat_pgmajfault[1m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host memory under memory pressure (instance {{ $labels.instance }})"
          description: "The node is under heavy memory pressure. High rate of major page faults"
      - alert: HostUnusualDiskReadRate
        expr: sum by (instance) (irate(node_disk_read_bytes_total[10m])) / 1024 / 1024 > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host unusual disk read rate (instance {{ $labels.instance }})"
          description: "Disk is probably reading too much data (> 50 MB/s)"
      - alert: HostOutOfDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/rootfs"}  * 100) / node_filesystem_size_bytes{mountpoint="/rootfs"} < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host out of disk space (instance {{ $labels.instance }})"
          description: "Disk is almost full (< 10% left)"
      - alert: HostOutOfInodes
        expr: node_filesystem_files_free{mountpoint ="/rootfs"} / node_filesystem_files{mountpoint ="/rootfs"} * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host out of inodes (instance {{ $labels.instance }})"
          description: "Disk is almost running out of available inodes (< 10% left)"
      - alert: HostUnusualDiskReadLatency
        expr: rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host unusual disk read latency (instance {{ $labels.instance }})"
          description: "Disk latency is growing (read operations > 100ms)"
      - alert: HostUnusualDiskWriteLatency
        expr: rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host unusual disk write latency (instance {{ $labels.instance }})"
          description: "Disk latency is growing (write operations > 100ms)"
      - alert: HostSwapIsFillingUp
        expr: (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host swap is filling up (instance {{ $labels.instance }})"
          description: "Swap is filling up (>80%)"
      - alert: HostPhysicalComponentTooHot
        expr: node_hwmon_temp_celsius > 75
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host physical component too hot (instance {{ $labels.instance }})"
          description: "Physical hardware component too hot"
  - name: Container Alerts
    rules:
      #- alert: ContainerMemoryUsage
      #  expr: (sum(container_memory_usage_bytes) BY (instance, name) / sum(container_spec_memory_limit_bytes) BY (instance, name) * 100) > 80
      #  for: 5m
      #  labels:
      #    severity: warning
      #  annotations:
      #    summary: "Container Memory usage (instance {{ $labels.instance }})"
      #    description: "Container Memory usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: ContainerCpuUsage
        expr: (sum by(instance, name) (rate(container_cpu_usage_seconds_total{name!=""}[3m])) * 100) > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container CPU usage (container {{ $labels.name }} on {{ $labels.instance }})"
          description: "Container CPU usage is above 300%"
      - alert: ContainerVolumeUsage
        #expr: (1 - (sum(container_fs_inodes_free) BY (instance) / sum(container_fs_inodes_total) BY (instance)) * 100) > 80
        expr: (1 - (sum by (instance, name)(container_fs_inodes_free{name!=""})) / (sum by (instance, name)(container_fs_inodes_total{name!=""})) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container Volume usage (container {{ $labels.name }} on {{ $labels.instance }})"
          description: "Container Volume usage is above 80%"
          #description: "Container Volume usage is above 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: ContainerVolumeIoUsage
        expr: (sum by(instance, name) (container_fs_io_current{name!=""}) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container Volume IO usage (container {{ $labels.name }} on {{ $labels.instance }})"
          description: "Container Volume IO usage is above 80%"
  - name: Traefik Alerts
    rules:
      - alert: TraefikHighHttp4xxErrorRateBackend
        expr: (sum(rate(traefik_service_requests_total{code=~"4.*"}[5m])) by (instance, service) / sum(rate(traefik_service_requests_total[5m])) by (instance, service) * 100) > 15
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Traefik high HTTP 4xx error rate backend (service {{ $labels.service }} on {{ $labels.instance }})"
          description: "Traefik backend 4xx error rate is above 5%"
      - alert: TraefikHighHttp5xxErrorRateBackend
        expr: (sum(rate(traefik_service_requests_total{code=~"5.*"}[5m])) by (instance, service) / sum(rate(traefik_service_requests_total[5m])) by (instance, service) * 100) > 15
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Traefik high HTTP 5xx error rate backend (service {{ $labels.service }} on {{ $labels.instance }})"
          description: "Traefik backend 5xx error rate is above 5%"
      - alert: TraefikEntrypointHighResponseTime
        expr: (sum (traefik_entrypoint_request_duration_seconds_sum{protocol="http"}) by (protocol, instance, entrypoint)) / (sum (traefik_entrypoint_requests_total{protocol="http"}) by (protocol, instance, entrypoint)) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Traefik entrypoint high response time ( entrypoint {{ $labels.entrypoint }} ({{ $labels.protocol }}) on {{ $labels.instance }})"
          description: "Traefik entrypoint response time is above 10s"
      - alert: TraefikServiceHighResponseTime
        expr: sum(traefik_service_request_duration_seconds_sum)by(instance, service, protocol) / sum(traefik_service_request_duration_seconds_count)by(instance, service, protocol) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Traefik service high response time ( service {{ $labels.service }} ({{ $labels.protocol }}) on {{ $labels.instance }})"
          description: "Traefik service response time is above 10s"