global:
  checkNewVersion: true
  sendAnonymousUsage: false

#Define HTTP and HTTPS entrypoints
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"
  #metrics:
  #  address: ":8082"

#Enable dashboard
#api:
#  dashboard: true
#  insecure: true

#Dynamic configuration will come from docker labels
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /configs
    watch: true

#Enable acme with http file challenge
certificatesResolvers:
  letsencrypt:
    acme:
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      storage: /acme.json
      httpChallenge:
        entryPoint: http

log:
  level: ERROR #- --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC

accessLog:
  filePath: /traefik.log
  bufferingSize: 100

#metrics:
#  prometheus:
#    entryPoint: metrics
#    buckets:
#      - 0.1
#      - 0.3
#      - 1.2
#      - 5.0
#    addEntryPointsLabels: true
#    addServicesLabels: true
