global:
  checkNewVersion: true
  sendAnonymousUsage: false

#Define HTTP and HTTPS entrypoints
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ':443'
    http:
      middlewares:
        - baseline-secureheaders@file
        - baseline-ratelimits@file
  metrics:
    address: ":8441"

#Enable dashboard
api:
  dashboard: true

#Dynamic configuration will come from docker labels and files
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /configs
    watch: true

#Enable acme with http file challenge
certificatesResolvers:
  letsencrypt:
    acme:
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory # LetsEncrypt Staging Server - uncomment when testing
      storage: /traefik/acme.json
      httpChallenge:
        entryPoint: http

log:
  level: ERROR #- --log.level=DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC

accessLog:
  filePath: /traefik/traefik.log
  bufferingSize: 100

metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true
